<?xml version="1.0" encoding="utf-8"?>
<!-- @@BEGIN_SDKSPLIT

  TEXTINPUT MANIFEST SCHEMA

  !!!WARNING!!!

  Don't make any changes to this schema.  Changes will affect a wide range of
  partners and can potentially break product and test code, as well as existing
  .appx packages and manifests. Please follow https://microsoft.sharepoint.com/teams/appxmanifest/SitePages/Home.aspx
  if you need to request any addition or modification.

@@END_SDKSPLIT -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://schemas.microsoft.com/appx/manifest/textinput"
           xmlns="http://schemas.microsoft.com/appx/manifest/textinput"
           xmlns:t="http://schemas.microsoft.com/appx/manifest/types"
           xmlns:f="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
           >

  <xs:import namespace="http://schemas.microsoft.com/appx/manifest/types"/>
  <xs:import namespace="http://schemas.microsoft.com/appx/manifest/foundation/windows10"/>

  <xs:element name="Capability" substitutionGroup="f:CapabilityChoice">
    <xs:complexType>
      <xs:attribute name="Name" type="t:ST_Capability_TextInput" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>